ALTER TABLE INACAP.CLIENTES
 DROP PRIMARY KEY CASCADE;

DROP TABLE INACAP.CLIENTES CASCADE CONSTRAINTS;

CREATE TABLE INACAP.CLIENTES
(
  RUT        VARCHAR2(12 BYTE),
  NOMBRE     VARCHAR2(50 BYTE),
  TELEFONO   INTEGER,
  DIRECCION  VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX INACAP.CLIENTES_PK ON INACAP.CLIENTES
(RUT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE INACAP.CLIENTES ADD (
  CONSTRAINT CLIENTES_PK
  PRIMARY KEY
  (RUT)
  USING INDEX INACAP.CLIENTES_PK
  ENABLE VALIDATE);

  ALTER TABLE INACAP.EMPLEADOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE INACAP.EMPLEADOS CASCADE CONSTRAINTS;

CREATE TABLE INACAP.EMPLEADOS
(
  USUARIO  VARCHAR2(50 BYTE),
  CLAVE    VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX INACAP.EMPLEADOS_PK ON INACAP.EMPLEADOS
(USUARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE INACAP.EMPLEADOS ADD (
  CONSTRAINT EMPLEADOS_PK
  PRIMARY KEY
  (USUARIO)
  USING INDEX INACAP.EMPLEADOS_PK
  ENABLE VALIDATE);

ALTER TABLE INACAP.ORDENES
 DROP PRIMARY KEY CASCADE;

DROP TABLE INACAP.ORDENES CASCADE CONSTRAINTS;

CREATE TABLE INACAP.ORDENES
(
  IDORDEN   INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP) NOT NULL,
  IDPIZZA   INTEGER,
  FECHA     TIMESTAMP(6),
  CANTIDAD  INTEGER,
  USUARIO   VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX INACAP.ORDENES_PK ON INACAP.ORDENES
(IDORDEN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE INACAP.ORDENES ADD (
  CONSTRAINT ORDENES_PK
  PRIMARY KEY
  (IDORDEN)
  USING INDEX INACAP.ORDENES_PK
  ENABLE VALIDATE);

ALTER TABLE INACAP.ORDENES ADD (
  CONSTRAINT ORDENES_FK1 
  FOREIGN KEY (IDORDEN) 
  REFERENCES INACAP.PIZZAS (IDPIZZA)
  ENABLE VALIDATE,
  CONSTRAINT ORDENES_R01 
  FOREIGN KEY (USUARIO) 
  REFERENCES INACAP.EMPLEADOS (USUARIO)
  ENABLE VALIDATE);

ALTER TABLE INACAP.PIZZAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE INACAP.PIZZAS CASCADE CONSTRAINTS;

CREATE TABLE INACAP.PIZZAS
(
  IDPIZZA  INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP) NOT NULL,
  TITULO   VARCHAR2(50 BYTE),
  PRECIO   INTEGER,
  IMAGEN   VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX INACAP.PIZZAS_PK ON INACAP.PIZZAS
(IDPIZZA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE INACAP.PIZZAS ADD (
  CONSTRAINT PIZZAS_PK
  PRIMARY KEY
  (IDPIZZA)
  USING INDEX INACAP.PIZZAS_PK
  ENABLE VALIDATE);

SET DEFINE OFF;
Insert into INACAP.PIZZAS
   (IDPIZZA, TITULO, PRECIO, IMAGEN)
 Values
   (1, 'Queso', 100, 'img.jpg');
Insert into INACAP.PIZZAS
   (IDPIZZA, TITULO, PRECIO, IMAGEN)
 Values
   (2, 'Margherita', 200, 'img.jpg');
Insert into INACAP.PIZZAS
   (IDPIZZA, TITULO, PRECIO, IMAGEN)
 Values
   (3, 'Hawaiana', 300, 'img.jpg');
COMMIT;
