//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb.EmpleadosServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPLEADOS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMPLEADOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLAVEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CLAVE {
            get {
                return this.CLAVEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLAVEField, value) != true)) {
                    this.CLAVEField = value;
                    this.RaisePropertyChanged("CLAVE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpleadosServiceReference.EmpleadosWSSoap")]
    public interface EmpleadosWSSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Leer", ReplyAction="*")]
        ProyectoWeb.EmpleadosServiceReference.LeerResponse Leer(ProyectoWeb.EmpleadosServiceReference.LeerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Leer", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoWeb.EmpleadosServiceReference.LeerResponse> LeerAsync(ProyectoWeb.EmpleadosServiceReference.LeerRequest request);
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        ProyectoWeb.EmpleadosServiceReference.ListarResponse Listar(ProyectoWeb.EmpleadosServiceReference.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoWeb.EmpleadosServiceReference.ListarResponse> ListarAsync(ProyectoWeb.EmpleadosServiceReference.ListarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Leer", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWeb.EmpleadosServiceReference.LeerRequestBody Body;
        
        public LeerRequest() {
        }
        
        public LeerRequest(ProyectoWeb.EmpleadosServiceReference.LeerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public LeerRequestBody() {
        }
        
        public LeerRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LeerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LeerResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWeb.EmpleadosServiceReference.LeerResponseBody Body;
        
        public LeerResponse() {
        }
        
        public LeerResponse(ProyectoWeb.EmpleadosServiceReference.LeerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LeerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoWeb.EmpleadosServiceReference.EMPLEADOS LeerResult;
        
        public LeerResponseBody() {
        }
        
        public LeerResponseBody(ProyectoWeb.EmpleadosServiceReference.EMPLEADOS LeerResult) {
            this.LeerResult = LeerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWeb.EmpleadosServiceReference.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(ProyectoWeb.EmpleadosServiceReference.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWeb.EmpleadosServiceReference.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(ProyectoWeb.EmpleadosServiceReference.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoWeb.EmpleadosServiceReference.EMPLEADOS[] ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(ProyectoWeb.EmpleadosServiceReference.EMPLEADOS[] ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpleadosWSSoapChannel : ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadosWSSoapClient : System.ServiceModel.ClientBase<ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap>, ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap {
        
        public EmpleadosWSSoapClient() {
        }
        
        public EmpleadosWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadosWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWeb.EmpleadosServiceReference.LeerResponse ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap.Leer(ProyectoWeb.EmpleadosServiceReference.LeerRequest request) {
            return base.Channel.Leer(request);
        }
        
        public ProyectoWeb.EmpleadosServiceReference.EMPLEADOS Leer(string usuario) {
            ProyectoWeb.EmpleadosServiceReference.LeerRequest inValue = new ProyectoWeb.EmpleadosServiceReference.LeerRequest();
            inValue.Body = new ProyectoWeb.EmpleadosServiceReference.LeerRequestBody();
            inValue.Body.usuario = usuario;
            ProyectoWeb.EmpleadosServiceReference.LeerResponse retVal = ((ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap)(this)).Leer(inValue);
            return retVal.Body.LeerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoWeb.EmpleadosServiceReference.LeerResponse> ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap.LeerAsync(ProyectoWeb.EmpleadosServiceReference.LeerRequest request) {
            return base.Channel.LeerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoWeb.EmpleadosServiceReference.LeerResponse> LeerAsync(string usuario) {
            ProyectoWeb.EmpleadosServiceReference.LeerRequest inValue = new ProyectoWeb.EmpleadosServiceReference.LeerRequest();
            inValue.Body = new ProyectoWeb.EmpleadosServiceReference.LeerRequestBody();
            inValue.Body.usuario = usuario;
            return ((ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap)(this)).LeerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWeb.EmpleadosServiceReference.ListarResponse ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap.Listar(ProyectoWeb.EmpleadosServiceReference.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public ProyectoWeb.EmpleadosServiceReference.EMPLEADOS[] Listar() {
            ProyectoWeb.EmpleadosServiceReference.ListarRequest inValue = new ProyectoWeb.EmpleadosServiceReference.ListarRequest();
            inValue.Body = new ProyectoWeb.EmpleadosServiceReference.ListarRequestBody();
            ProyectoWeb.EmpleadosServiceReference.ListarResponse retVal = ((ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoWeb.EmpleadosServiceReference.ListarResponse> ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap.ListarAsync(ProyectoWeb.EmpleadosServiceReference.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoWeb.EmpleadosServiceReference.ListarResponse> ListarAsync() {
            ProyectoWeb.EmpleadosServiceReference.ListarRequest inValue = new ProyectoWeb.EmpleadosServiceReference.ListarRequest();
            inValue.Body = new ProyectoWeb.EmpleadosServiceReference.ListarRequestBody();
            return ((ProyectoWeb.EmpleadosServiceReference.EmpleadosWSSoap)(this)).ListarAsync(inValue);
        }
    }
}
